AllCops:
  TargetRubyVersion: 2.3
  NewCops: disable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Max: 150

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Style/SpecialGlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false
